name: Build, Push Docker Images to Docker Hub, and Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the frontend Docker image
    - name: Build frontend Docker image
      run: |
        cd ./client
        npm install --legacy-peer-deps
        docker build -t client-image:latest -f ./Dockerfile .

    # Step 5: Tag frontend Docker image for Docker Hub
    - name: Tag frontend Docker image
      run: |
        docker tag client-image:latest pavanprasaf/tranceci:client-latest

    # Step 6: Build the backend Docker image
    - name: Build backend Docker image
      run: |
        cd ./server
        npm install
        docker build -t server-image:latest -f ./Dockerfile .

    # Step 7: Tag backend Docker image for Docker Hub
    - name: Tag backend Docker image
      run: |
        docker tag server-image:latest pavanprasaf/tranceci:server-latest

    # Step 8: Push the frontend Docker image to Docker Hub
    - name: Push frontend Docker image to Docker Hub
      run: |
        docker push pavanprasaf/tranceci:client-latest

    # Step 9: Push the backend Docker image to Docker Hub
    - name: Push backend Docker image to Docker Hub
      run: |
        docker push pavanprasaf/tranceci:server-latest

  deploy-client:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Client on EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.CLIENT_EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Install Docker if not installed
          if ! command -v docker &> /dev/null; then
            sudo apt-get update -y
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi
          # Pull and run client container
          docker pull pavanprasaf/tranceci:client-latest
          docker stop client-container || true
          docker rm client-container || true
          docker run -d --name client-container -p 3001:3001 pavanprasaf/tranceci:client-latest

  deploy-server:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Server on EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Install Docker if not installed
          if ! command -v docker &> /dev/null; then
            sudo apt-get update -y
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi
          # Pull and run server container
          docker pull pavanprasaf/tranceci:server-latest
          docker stop server-container || true
          docker rm server-container || true
          docker run -d --name server-container -p 3000:3000 pavanprasaf/tranceci:server-latest
