name: Mirror to GitLab

on:
  push:
    branches:
      - main  # Specify the branches you want to mirror

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch the entire history to avoid shallow update issues

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Pull latest changes from GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Add GitLab remote
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/nun2884945/trance.git
          
          # Fetch and merge changes from GitLab main branch
          git fetch gitlab
          git merge gitlab/main --allow-unrelated-histories

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Push changes to GitLab without force
          git push gitlab main
          git push gitlab --tags
