name: Mirror to GitLab 

on:
  push:
    branches:
      - main  # Specify the branches you want to mirror

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Add GitLab remote
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/nun2884945/trance.git

          # Push to GitLab
          git push -u gitlab --all
          git push -u gitlab --tags
